use_frameworks!

platform :ios, '9.0'

target 'ProjectIntialDesigns_Example' do
  pod 'ProjectIntialDesigns', :path => '../'

  target 'ProjectIntialDesigns_Tests' do
    inherit! :search_paths

    
  end
end
